language: objective-c
osx_image: xcode8.2

env:
  - DESTINATION='platform=macOS,arch=x86_64'
  - DESTINATION='platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72'

script:
  - set -o pipefail && xcodebuild -scheme fut -destination "$DESTINATION" test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | xcpretty
