language: objective-c
osx_image: xcode8.2

env:
  global:
  - IOS_SDK=iphonesimulator10.2
  - MACOS_SDK=macosx10.12

  matrix:
  - DESTINATION="OS=10.0,name=iPhone 7 Plus" SDK="$IOS_SDK"
  - DESTINATION="OS=9.0,name=iPhone 6" SDK="$IOS_SDK"
  - DESTINATION="OS=8.1,name=iPhone 4S" SDK="$IOS_SDK"

  - DESTINATION="arch=x86_64" SDK="$MACOS_SDK"
  
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -scheme fut -sdk "$SDK" -destination "$DESTINATION" test | xcpretty
